### ISSUE TITLE
AWL.Citrix.Receiver.WebVS (Incompatible)

### ISSUE THREAD

**Issue by bkvinoth** [awl-techniek/AWL-Citrix-Storefront#2]
I get error shown in the visual studio 2015 enterprise and 2017 wit all extension installed.
Please suggest

**Comment by manuelmarucco** [comment]
OPTION 1) install the` Node.js Tools` extension for VS and install then `NPM Task Runner` extension which you can download from here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner .

OPTION 2) As the building/installation procedure for `AWL-Citrix-Storefront/src/AWL.Citrix.Reciever.Web` says, you need Node.js and `npm package explorer` first ( https://nodejs.org/en/download/ ). Then execute the following commands: 

(quote from readme.md)

i) Run `npm install` from the AWL Citrix Reciever Web directory to install the required dependencies.
ii) Build and bundle the source files by running `npm run build`. All the build scripts can be found in the package.json file.

**Comment by rkossen** [comment]
Hi,

Thanks Manual for the explanation. This is indeed the procedure.
